### ISSUE TITLE
Discovery Tour: Ancient Greece / Egypt

### ISSUE THREAD

**Issue by gryphius** [heimschulung/heimschulung.github.io#2]
**Themengebiet**
Reisen, Geschichte

**Beschreibung.**
"Discovery Tour: Ancient Greece" , bzw "Discovery Tour: Ancient Egypt" erlauben es, in das antike Griechenland bzw. Ägypten  zu reisen und mit geführten Rundgängen oder freier Erkundung die interessanten Sehenswürdigkeiten und Personen kennenzulernen.

Hinweise: Dieses sind spezielle Versionen des Spiels "Assassin's Creed". Die "Discovery Tours" enthalten im Gegensatz zum normalen Spiel keine Kämpfe. Systemanforderungen beachten, es wird ein moderner PC mit einer guten Grafikkarte benötigt.

**Link**
https://store.ubi.com/upc/de/discovery-tour--ancient-greece-by-ubisoft/5d4041f35cdf9a07d09464ad.html?edition=Das%20antike%20Griechenland

https://store.ubi.com/upc/de/discovery-tour-by-assassin-s-creed-ancient-egypt/5a7d728d0c8ee45b54018f25.html?edition=Ancient%20Egypt

**Comment by oetiker** [comment]
danke! ist eingebaut!
