### ISSUE TITLE
Other Languages

### ISSUE THREAD

**Issue by whoo** [heimschulung/heimschulung.github.io#4]
Hi,
Can we propose merge request with different language ? (FR/EN).

Regards,
Whoo

**Comment by oetiker** [comment]
Hi Whoo,

We are focusing on german content (mostly). As such, translating the website will not be very helpful as it does not contain original content only liks to 3rd party content. BUT feel free to Fork it and create a version in your prefered language, replacing adding appropriate resources.

cheers
tobi
